### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Lada496**
#### What I learned
- how to test asynchronous functions such as fetch (related commits: [learned how to test asynchronous functions](https://github.com/Lada496/stand-on-the-sholders-of-giants/commit/b222fb05481d37e1672408737ed616e81fb63af9), [learned mock and spies](https://github.com/Lada496/stand-on-the-sholders-of-giants/commit/9788badbb673ba565f4df02e2fa03be8f440a1d3))
- how to test react apps including redux (related commits: [learned snapshot testing](https://github.com/Lada496/stand-on-the-sholders-of-giants/commit/83305d0a55d1aa6488907a1724fbab400b9de7e1), [learned how to test stateful components](https://github.com/Lada496/stand-on-the-sholders-of-giants/commit/cf9891a4c4790643d9eb49c2ae8e92a1084fa71d), [learned how to test connected components](https://github.com/Lada496/stand-on-the-sholders-of-giants/commit/37db3120b03373ac8209f362ef7d3134f36ed88c), [learned how to test reducers](https://github.com/Lada496/stand-on-the-sholders-of-giants/commit/ade1cc35cc470c39b9c1ec80709a6227899fb1ae), [learned how to test actions](https://github.com/Lada496/stand-on-the-sholders-of-giants/commit/fe68e21c7f52fd98f251518d3df18a8bc9e0fa40))
- how to set up husky (related commit: [setup husky](https://github.com/Lada496/stand-on-the-sholders-of-giants/commit/69bca74e10b693f665bc59dcbca4f8308947f024)): The problem was I needed to run different scripts depending on repos whereas husky simply runs npm test in their root repo when I run git commit. I think there should be a more elegant solution though...

#### What I thought
- snapshot test is super convenient!
- I'm still looking for benefits to use enzyme instead of react testing library. I think I can try both and compare by myself.

#### Others
I'm planing to do a small project with TypeScript to review what I learned so far. I hope I can dig into test with functional components more.

### CODE REVIEW

**Comment by koh1project** [comment]
You did a great job, and I was really amazed by what you have done a lot!

> how to set up husky (related commit: [setup husky](https://github.com/Lada496/stand-on-the-sholders-of-giants/commit/69bca74e10b693f665bc59dcbca4f8308947f024)): The problem was I needed to run different scripts depending on repos whereas husky simply runs npm test in their root repo when I run git commit. I think there should be a more elegant solution though...
  
I think you can use commands in `.husky/pre-commit` by using the Unix command instead of the ones in the root npm script. Looking at the first line of pre-commit, it shows `#!/usr/bin/env sh` means it uses shell script and just executes the npm test command.

**Comment by Lada496** [comment]
@koh1project Thanks for your suggestion! I modified .husky/pre-command to see if my understanding is correct.
Please let me know if I'm doing wrong.
p.s I believe we can survive unix environments if we know `pwd` and `cd`.

**Comment by kei95** [comment]
Thanks for the advice @koh1project! It seems like her change made it work👍 

>What I thought
>snapshot test is super convenient!

That's good you found it convenient! One thing to be careful of is that Snapshot testing makes you feel like you wrote a test but it's essential to understand its use case🙂 It just literally takes the snapshot of the file so doesn't offer you to check its behavior(e.g. when you click on this component, what should happen. etc.). It's surely convenient if you want to make sure that changes in other places affected the file unexpectedly. This means it doesn't give you any confidence when you make refactor in the file because ANY changes made in the file break the test, while what really want to confirm is the change you are making is not changing the behavior of the component/logic at the end.

> I'm still looking for benefits to use enzyme instead of react testing library. I think I can try both and compare by myself.

I personally prefer react-testing-library over enzyme, because enzyme relatively cares more about implementation detail rather the end result of the component. It's the basic thought that tests should care end result more than the implementation detail. With that being said, I want to see what you have discovered during your research and its conclusion. 

### So here's a homework;
Please put your research together and give us some output in any shape like an article.

> Others
> I'm planing to do a small project with TypeScript to review what I learned so far. I hope I can dig into test with functional components more.

That's good! Looking forward to see that one coming!

**Comment by Lada496** [comment]
@kei95 @koh1project
I wrote about comparison b/w Enzyme and React Testing Library.
Please find the email invitation of the article on Notion.

**Pull request merged**
